export const ACTIONS = {
    FILTER_: 'FILTER_',
    SET_DATA: 'SET_DATA',
    SHOW_MODAL: 'SHOW_MODAL',
    HIDE_MODAL : 'HIDE_MODAL',
    SET_ID_MODIFY_USER: 'SET_ID_MODIFY_USER',
    ADD_NEW: 'ADD_NEW',
    REMOVE_ITEM: 'REMOVE_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM'

}